name: Daily TRM Ingestion Pipeline

# El 'on' define los disparadores (Triggers)
on:
  schedule:
    # Se ejecuta a las 12:00 UTC (8:00 AM COL aproximadamente) todos los días
    - cron: '0 12 * * *'
  workflow_dispatch: # Esto nos permite ejecutarlo manualmente desde la pestaña "Actions" de GitHub

jobs:
  etl_process:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Copiando el código del repositorio
        uses: actions/checkout@v4

      - name: 2. Configurando Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          # El 'cache' acelera las ejecuciones futuras guardando las librerías
          cache: 'pip'

      - name: 3. Instalando dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Ejecutando el pipeline de Ingesta
        env:
          # Aquí mapeamos el Secret que creaste en GitHub con la variable que espera Python
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: python ingestor_trm.py